import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-6">
              <h1 className="text-center">Quiz App</h1>
              <h2 className="text-center">by Erik Torck</h2>
            </div>
          </div>
          <div className="row justify-content-center">
            <div className="col-6">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
